services:
  assistant-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assistant-server
    env_file:
      - .env
    volumes:
      - /run/cups/cups.sock:/run/cups/cups.sock
    environment:
      CUPS_SERVER: /run/cups/cups.sock
      OLLAMA_HOST: http://host.docker.internal:11434
      API_HOST: 0.0.0.0
      API_PORT: 8000
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: no #Change in future if change monitoring
